### ISSUE TITLE
Visual Studio Community and SDK 7.1

### ISSUE THREAD

**Issue by FrenchBen** [vslavik/winsparkle#104]
It seems that the above VS Community and SDK 7.1 on Windows 10 are not compatible. 

I found some posts on installing/removing stuff, such as:
http://www.mathworks.com/matlabcentral/answers/95039-why-does-the-sdk-7-1-installation-fail-with-an-installation-failed-message-on-my-windows-system

Which is quite annoying - Anyway to bump up the SDK to 10 instead of 7.1?

**Comment by vslavik** [comment]
> It seems that the above VS Community and SDK 7.1 on Windows 10 are not compatible.

That’s a rather extraordinary claim, please back it up with solid evidence — I see no indication of anything like that so far. That random post in an unrelated forum says no such thing and doesn’t in fact seem relevant to this issue at all. FWIW, Microsoft is good about documenting differences and doesn’t indicate anything of the sorts either.

It’s unfortunately very hard to even guess what the *actual* problem is, because you didn’t say anything about the symptoms. My guess is that you didn’t select XP targeting in the installer, that’s all. If that’s not the case and you have solid evidence that projects using 7.1 SDK won’t compile in VSC2015, then…

> Anyway to bump up the SDK to 10 instead of 7.1?

…you are welcome to come up with a PR fixing things and I’ll gladly accept it, provided that *it doesn’t change compilation with full MSVS versions*. Project files are just MSBuild files and you can easily put such things as target toolset or SDK into a `.props` file for user customization, maybe even autodetect. 

But the “official” version of WinSparkle will continue to use the 7.1 SDK, not because I particularly want to (I don’t), but because that’s the latest/only one that the `v140_xp` toolset is capable of using. And even though Windows XP should burn in hell already, it just won’t, and a component like WinSparkle simply has to continue to support it for the foreseeable future.

**Comment by ThomasBarnekow** [comment]
Windows XP support ended two years ago (on [April 8, 2014](http://windows.microsoft.com/en-us/windows/end-support-help)). If Microsoft stopped providing updates, why do you have to continue to support Windows XP with every new release? You could provide one last release supporting Windows XP (e.g., the current one) and then upgrade the SDK if you see benefits.

Or do you have a specific reason for wanting/needing to support Windows XP?

**Comment by vslavik** [comment]
> Or do you have a specific reason for wanting/needing to support Windows XP?

Yes. There's this pesky thing called "[reality](https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0)" that you have to consider. 

WinSparkle will continue to support deployment to XP until XP dies out or until there's a damn good *technical* reason not to which makes sacrificing it worth doing.

**Comment by ThomasBarnekow** [comment]
OK, "reality" says Windows XP has a 12% share of all Windows installations (10.63% of all OSes). What percentage of those will depend on WinSparkle (also given that many software vendors - like Microsoft - will have ended support for Windows XP)? 1? 5? 10? 20? Not sure whether you should continue using an SDK that you don't want to use any longer to support a very small group of users IF a much larger group of users would benefit from using another one. However, I don't know what the benefits of using a later SDK would really be. You will know that better.

**Comment by FrenchBen** [comment]
Didn't mean to open up such heated discussion - There were a few conflicting packages that prevented the SDk 7.1 from installing. 
After a clean setup/update I was able to install the necessary components.

**Comment by vslavik** [comment]
> Not sure whether you should continue using an SDK

Please don’t hijack issues with off-topic opinions in the future, thanks.
