### ISSUE TITLE
[question] does winsparkle support wxwidgets?

### ISSUE THREAD

**Issue by standtall007** [vslavik/winsparkle#105]
Hi i would love to have this integrated into my application, but i am currently using wxWidgets, and would like to know if WinSparkle supports wxWidgets?

Thanks in advance,
David Mortensen.

**Comment by standtall007** [comment]
Sorry, i just realized that it does support wxWidgets :) Sorry and i'll close this question asap, thanks :)

David Mortensen.

**Comment by vslavik** [comment]
It’s not really that WinSparkle “supports” wxWidgets (although it is implemented using it and I use it in my own wx-based app…). It’s more accurate to say that WinSparkle is *agnostic* w.r.t. your GUI toolkit — it really doesn’t give a damn.

The API is such that you can use it from whatever and don’t need to integrate it deeply, e.g. by having to cooperate with your app’s event loop (WinSparkle runs its own on its own completely independent thread), precisely so that you can use it with wx, Qt, MFC, WPF or whatever.

**Comment by standtall007** [comment]
Hi vslavik, and thank you very much for the clarification :) it helps me a lot :+1:
