### ISSUE TITLE
Winsparkle won't follow redirects

### ISSUE THREAD

**Issue by ThanosSiopoudis** [vslavik/winsparkle#109]
If the item URL in the appcast xml file points to a redirect location (to prevent hotlinking for example), WinSparkle fails when attempting to download the file, as it won't follow the LOCATION header.

The runtime_error thrown is "Cannot save update file"

**Comment by vslavik** [comment]
Please be a good developer and reports bugs as you’d want bugs reported to you. *Always* include [steps to reproduce](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

At the barest minimum, reproduction steps must include specifics, i.e. the URL of the feed that doesn’t work and preferably (it’s dead simple, so there’s no excuse to not do it, really) a patch against the included example that reproduces the issue.

WinInet handles redirects automatically be default. It would be very strange indeed if that didn’t work in WinSparkle, no least *because I use them myself*.

**Comment by ThanosSiopoudis** [comment]
Thanks, I'm trying to gather all the data before I can help you with what's going on. Bear with me, it's my first crack at Winsparkle, and there's a lot of code to go through.

It seems that `InternetOpenUrlA` is not the issue, as it DOES follow the redirect and actually downloads the file data.

The problem seems to be in the method that sets the filename, and not actually downloading the file.

Here's an appcast I've created that doesn't work, feel free to try it, and let me know if you don't have access to it:
https://rink.hockeyapp.net/api/2/apps/132dac157c62466b990de9d58ac36427.rss
