### ISSUE TITLE
Encoding issue in WinSparkle UI

### ISSUE THREAD

**Issue by jiakuan** [vslavik/winsparkle#129]
Hi there,

I'm using WinSparkle 0.5.3, and I got a strange encoding issue in WinSparkle UI as below:

<img width="404" alt="screen shot 2017-02-20 at 15 41 01" src="https://cloud.githubusercontent.com/assets/533236/23116010/360a9576-f783-11e6-8595-46e2d6b4d035.png">

<img width="566" alt="screen shot 2017-02-20 at 16 39 04" src="https://cloud.githubusercontent.com/assets/533236/23117545/2766eb98-f78b-11e6-89fc-ed0c284ec2ff.png">

The AppCast URL is: https://dist-v2.wisetime.io/appcast-win.xml

Is it a bug in WinSparkle or something wrong in my AppCast file? Thanks.

**Comment by jiakuan** [comment]
This one may be relevant to https://github.com/vslavik/winsparkle/issues/123?

**Comment by vslavik** [comment]
> This one may be relevant to #123?

No. That didn't add random garbage.

> The AppCast URL is: https://dist-v2.wisetime.io/appcast-win.xml

This feed is very obviously not the one you used to make your first screenshot. The two screenshots are mutually inconsistent, clearly using different feeds. Please don't do that, it makes diagnosing harder. This feed URL alone is not enough to reproduce your screenshots.

I don't know what's going on (on its surface, seems impossible to happen in unmodified WinSparkle). You need to either provide precise reproduction instructions (i.e. a patch against WinSparkle's example showing the problem) or debug it yourself. It's impossible to fix without having all information.

>  or something wrong in my AppCast file?

Your feed is *definitely* broken, though. It doesn't provide any sparkle attributes because you use a wrong namespace (http, not https).

As a side note, you may want to change your code to use the standard `sparkle:` prefix instead of `ns0:`  — while they are equivalent for *namespaces-aware XML parser* (which WinSparkle currently uses), they are different for non-aware ones (such as Sparkle's… and WinSparkle may be changed to require `sparkle:` prefix in the future).

**Comment by jiakuan** [comment]
@vslavik Thanks for your detail answers.

The feeds for both screenshots are exactly the same, I just changed the version in my source code in IDE so that I can test both auto-update behaviours.

I also tried to point to this example feed: https://winsparkle.org/example/appcast.xml (also changed my app number to 1.1.0)

And I got the same encoding issue:
<img width="575" alt="screen shot 2017-02-21 at 12 00 36" src="https://cloud.githubusercontent.com/assets/533236/23150289/77eab318-f82d-11e6-9bdd-262bafa8bae8.png">

Which is very strange. Looks like it's not related to the appcast URL.

I'm investigating more and trying to run from the WinSparkle examples. I will keep you updated.

**Comment by jiakuan** [comment]
I have verified that this was caused by other parts of my code. Thanks for your time. I'm closing this one now.

**Comment by vslavik** [comment]
> I have verified that this was caused by other parts of my code.

For future reference, *how?* Did you make modifications to WinSparkle? If yes, that's what you should have investigated before filing an issue (as the obvious most likely case), but if not, then WinSparkle should arguably be "hardened" against making whatever mistake this was.

My guess before was that this was locale-related (seeing how the characters are well-formed Chinese, not garbage); now the only other possibility I can think of are some not-NULL-terminated strings somewhere.

**Comment by jiakuan** [comment]
Yes, you are right. It was string issues when passing companyName, appName, appVersion to this function win_sparkle_set_app_details() - overlooked that bit. It's nothing to do with WinSparkle.

Apologies about this.
