### ISSUE TITLE
Not able to build Winsparkle code

### ISSUE THREAD

**Issue by kguduri** [vslavik/winsparkle#138]
translations\translations.rc(1): error RC2135: file not found: ar.mo

all the translations file are not available adding the screen shot for the same, Followed the same steps that are mentioned in "Building from Sources"

![image](https://user-images.githubusercontent.com/27999771/26873811-c807aedc-4b98-11e7-8eec-022335d12ec4.png)

Please help me on this as soon as possible.

Or is there any other way where i can remove/hide the "Skip this version".

**Comment by vslavik** [comment]
> as soon as possible.

I didn't realize you were paying for support, so maybe tone it down a notch...

If you want fast help, you should start with actually describing what you did in meaningful detail, such as at least mentioning basics like the exact compiler version used or providing full (verbose!) compilation log.

The little that is visible in the censored screenshot indicates that the normal build process was *not* run, because the targets from `WinSparkle.Targets` were *not* executed. I don't see how that's possible unless you modified something.

Enable build logging, investigate.

**Comment by kguduri** [comment]
I have done the following to get the latest code 
$ git clone git://github.com/vslavik/winsparkle.git
$ cd winsparkle
$ git submodule init
$ git submodule update

Opened WinSparkle.sln in visual stuido 2015 and tried building the solution but the build fail with the following messages
translations\translations.rc(1): error RC2135: file not found: ar.mo
3>
3>
3>translations\translations.rc(2): error RC2135: file not found: be.mo
3>
3>
3>translations\translations.rc(3): error RC2135: file not found: bg.mo
3>
3>
3>translations\translations.rc(4): error RC2135: file not found: bs.mo
3>
3>
3>translations\translations.rc(5): error RC2135: file not found: ca_ES.mo
3>
3>
3>translations\translations.rc(6): error RC2135: file not found: co.mo
3>
3>
3>translations\translations.rc(7): error RC2135: file not found: cs.mo
3>
3>
3>translations\translations.rc(8): error RC2135: file not found: da.mo
3>
3>
3>translations\translations.rc(9): error RC2135: file not found: de.mo
3>
3>
3>translations\translations.rc(10): error RC2135: file not found: el.mo
3>
3>
3>translations\translations.rc(11): error RC2135: file not found: es.mo
3>
3>
3>translations\translations.rc(12): error RC2135: file not found: eu.mo
3>
3>
3>translations\translations.rc(13): error RC2135: file not found: fr.mo
3>
3>
3>translations\translations.rc(14): error RC2135: file not found: fy_NL.mo
3>
3>
3>translations\translations.rc(15): error RC2135: file not found: ga.mo
3>
3>
3>translations\translations.rc(16): error RC2135: file not found: he.mo
3>
3>
3>translations\translations.rc(17): error RC2135: file not found: hr.mo
3>
3>
3>translations\translations.rc(18): error RC2135: file not found: hu.mo
3>
3>
3>translations\translations.rc(19): error RC2135: file not found: hy.mo
3>
3>
3>translations\translations.rc(20): error RC2135: file not found: id.mo
3>
3>
3>translations\translations.rc(21): error RC2135: file not found: it.mo
3>
3>
3>translations\translations.rc(22): error RC2135: file not found: ja.mo
3>
3>
3>translations\translations.rc(23): error RC2135: file not found: kk.mo
3>
3>
3>translations\translations.rc(24): error RC2135: file not found: ko.mo
3>
3>
3>translations\translations.rc(25): error RC2135: file not found: nb.mo
3>
3>
3>translations\translations.rc(26): error RC2135: file not found: nl.mo

**Comment by vslavik** [comment]
Once again: something is broken with your VS. Enable VERBOSE logging. INVESTIGATE. I have neither access to your machine nor a crystal ball, I can't miraculously know what is broken on your computer. You can. Look into it. Debug it. You're a developer, that's what developers *do*.

**Comment by johnwbyrd** [comment]
You probably do not have nuget installed.

@vslavik, you should probably explain somewhere that Nuget.CommandLine is required in order to install the GetText.Tools packages from packages.xml.

**Comment by vslavik** [comment]
> @vslavik, you should probably explain somewhere that Nuget.CommandLine is required in order to install the GetText.Tools packages from packages.xml.

Except that NuGet [is bundled with Visual Studio since 2012](https://docs.microsoft.com/en-us/nuget/guides/install-nuget).

**Comment by fagutavikslavik** [comment]
slavik _does_ what all slaviks _do_ hurr _durr_

**Comment by raspopov** [comment]
@vslavik This issue happens when WinSparkle refreshed by latest **[bakefile](https://github.com/vslavik/bakefile)**, for example the newly generated "[WinSparkle-2015.vcxproj](https://github.com/vslavik/winsparkle/blob/master/WinSparkle-2015.vcxproj)" and "[WinSparkle-2015.vcxproj.filters](https://github.com/vslavik/winsparkle/blob/master/WinSparkle-2015.vcxproj.filters)" files have no more next line: 

`<Import Project="WinSparkle.targets" />`

i.e. "[WinSparkle.Targets](https://github.com/vslavik/winsparkle/blob/master/WinSparkle.Targets)" has not  been included in the **[bakefile](https://github.com/vslavik/bakefile)** build of "[WinSparkle.bkl](https://github.com/vslavik/winsparkle/blob/master/WinSparkle.bkl)" and so .mo-files are not produced from .po-files by GetText.Tools.

**Comment by matthiesenj** [comment]
Importing `Winsparkle.targets` is also missing from `WinSparkle-2012.vcxproj`. It's easily solvable by adding `<Import Project="WinSparkle.targets" />` to the import group, but the Bakefile warning at the top suggest it's not the right solution.

Building in VS2012 also has a few other issues:
- in signatureverifier.cpp, the pointers `bio` and `*dsa` are explicitly initialized to NULL. This is a C++11? feature, but the pointers are initialized in their respective class ctors anyway, so setting them to NULL is redundant.
- error LNK2001: unresolved external symbol __imp__SHAAutoComplete@8

That's as far as I got - until the linker error is resolved (name mangling issue, maybe?), I don't know if there are other problems.

I am wondering which VS version is normally supported by the project, because clearly not all of them are verified to be buildable, If we can't maintain support for all of them, maybe we should remove those that aren't supported? (or move them to unmaintained branches so people at least have the option to build older versions with older VS).

**Comment by vslavik** [comment]
> but the Bakefile warning at the top suggest it's not the right solution.

That can be ignored; other project files were manually modified too. My plan is to merge them all into a single version-agnostic project and drop pre-2010 support. 

> EDIT: This can be fixed by adding shlwapi.lib to Additional Dependencies in the Librarian section of WinSparkle_wx. The dependency isn't referenced in any of the other vcxproj files either, so is this a problem for all the VS projects?

It seems to be in '15 and '17 ones, so yes, that's the fix. Generally speaking, diffing vcxproj files between latest and whatever doesn't work should reveal the cause. But see above, I mean to fix this mess.

> I am wondering which VS version is normally supported by the project, 

Well, I use 2017 (soon '19) and it seems not many people use anything as old as 2012, seeing how long this problem was there.
