### ISSUE TITLE
Change orange icon to some own

### ISSUE THREAD

**Issue by romaromaniv** [vslavik/winsparkle#140]
![image](https://user-images.githubusercontent.com/28062488/27240530-bfcefdb4-52dd-11e7-90c8-4175fb73c332.png)

How it is possible? Could you please add such possibility?
Thanks.

**Comment by vslavik** [comment]
The icon is taken from your application. This is a fallback icon used only if you messed up.

Search the repository's code for "icon" for details. Or the included example app — that's why it's there.

Well-done, well-reasoned PRs improving the behavior (if you think there's anything to improve) are welcome. But this really just looks like you omitting the icon and so breaking more than just WinSparkle.

**Comment by romaromaniv** [comment]
Hm, could you please specify a little where should be located and how should be named application ico file?

For my case "appicon.ico" (I've found the name in repo) or "appexename.ico" (general google answer), which located in the same folder where exe file, does not work. Thanks in advance.

**Comment by vslavik** [comment]
@romaromaniv WinSparkle uses the same icon Windows OS uses. How to add an icon that Windows OS will present for the executable is well documented in MSDN and has no direct relationship to WinSparkle — it's just standard, run-of-the-mill win32 stuff. Short version (but *do* read MSDN docs!) is that it's the first icon in the resources, both by order and alphabetically.

As I also already said, the `example_psdk` sample shows you how it's done. Look at it.
