### ISSUE TITLE
Update window not visible when app main window is minimized

### ISSUE THREAD

**Issue by johnmurphy01** [vslavik/winsparkle#151]
We are running a WPF application that currently uses WinSparkle(version `0.5.7`). We are following the recommended way to set up auto updates:

```
win_sparkle_set_app_details("Company", "Application", string.Format("{0}", System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString()));
win_sparkle_set_appcast_url("http://sparkleurl.com");
win_sparkle_set_update_check_interval(3600);
win_sparkle_set_automatic_check_for_updates(1);
win_sparkle_init();
```

When we launch the application, WinSparkle does indeed display the update UI. However, if we then minimize our application and then WinSparkle attempts a subsequent auto update check, the window is not available. It's as if the update UI is somewhere out of the bounds of the desktop viewport.

At the point that this issue occurs, the only way to "fix" it is to close all windows associated with our application.

We weren't sure if this was a regression or a new issue since we saw this issue(somewhat related) https://github.com/vslavik/winsparkle/issues/46

**Comment by vslavik** [comment]
Please [follow these instructions](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html). If you submit a bug report, presumably it's because you'd like something to be *done* about the bug. That's only possible if you describe the bug well, i.e. when you, crucially, provide *reproduction instructions*: at minimum, that includes *full code* (ideally in a form of patch against WinSparkle example) and accurate, detailed, exact steps to perform to reproduce the issue. 

That you use WPF is in all likelihood irrelevant. What exactly your secret application code does, what windows it has, with what properties etc., on the other hand, is all highly relevant and probably explanatory — but unfortunately missing from this issue.

As you observed, #46 may be relevant. Therefore the most logical first thing to do is to use a debugger  and investigate why the code that fixed #46 doesn't work — that's straightforward and not particularly time-consuming work. Because as of now you are the only person with access to reproduction case, you are also the only person that can actually *do* it and provide some insight. Can you please do it and share any findings (ideally, of course, in the form of a patch)?

Thanks!

**Comment by johnmurphy01** [comment]
Hopefully this will be enough information for you to replicate and identify the bug. I am providing a zip file containing a sample application that makes the same WinSparkle calls that our production application makes. Here are the replication steps:

- Launch the sample application
Observe that the WinSparkle update UI will appear with the new version.

- Click "Remind me Later"
- Go into the registry and navigate to: `HKEY_CURRENT_USER\Software\Company\Application\WinSparkle`
- Set the `LastCheckTime` timestamp to a value one hour prior. For example if the current time is 11:10AM, modify the value to be a timestamp that is for 10:15AM on the same day.
- Run the application again except this time minimize the application Window. Wait until the time reaches one hour after the current `LastCheckTime`
Observe that the WinSparkle update UI will not appear but is present in the task bar. Trying to click on the taskbar item will not make the UI appear.

[WinSparkleTestApplication.zip](https://github.com/vslavik/winsparkle/files/1536165/WinSparkleTestApplication.zip)

**Comment by vslavik** [comment]
Again: it's best to try to reproduce in some *reasonable* way. Did you try to reproduce it in the included sample? Did you try to reproduce it with some small modifications to the sample? If not, please do — it's a reasonable thing to do, trying to narrow down the cause. Which, again, is unlikely to have anything to do with WPF.

**Comment by johnmurphy01** [comment]
I feel like the sample included with the replication steps are more than _reasonable_. Since you are the maintainer of the repo, any clearly defined issue should warrant further investigation. If I were more familiar with C++, I would gladly fix the issue myself and submit a PR. As it stands, I've provided you a very simple and consice application and it should be very simple for you to identify the root cause.

**Comment by danielgary** [comment]
@johnmurphy01 You misspelled concise.

**Comment by johnmurphy01** [comment]
@vslavik I've committed a PR to resolve this issue. If you could please review and let me know if there are any issues and/or merge into `master` at your earliest convenience, we'd greatly appreciate it.

https://github.com/vslavik/winsparkle/pull/152

Thanks!

**Comment by vslavik** [comment]
@johnmurphy01 Thank you, much appreciated! (And sorry for the delay, it took me a bit to gather courage to return to the bizarre and now mostly-deleted/edited drive-by trolling by your [Gateway Apps](http://www.gatewayapps.com) colleague).

**Comment by vslavik** [comment]
Reverse engineering your patch, this is the minimal reproduction I was after: 
```diff
diff --git a/examples/psdk/app_psdk.c b/examples/psdk/app_psdk.c
index d331722..a04dc5d 100644
--- a/examples/psdk/app_psdk.c
+++ b/examples/psdk/app_psdk.c
@@ -62,6 +62,7 @@ void OnCheckForUpdates(HWND hwnd,
 {
     if ( id == IDB_CHECK_FOR_UPDATES )
     {
+        ShowWindow(g_hwndMain, SW_MINIMIZE);
         /* Manually check for updates. This is user-initiated action and
            always shows visible UI. You only need to call it if you have
            a "Check for updates" menu item, otherwise win_sparkle_init()
```

IOW, unrelated to WPF and much  more serious issue, thanks again for catching it.

**Comment by johnmurphy01** [comment]
@vslavik no problem! Thank you for investigating further
