### ISSUE TITLE
WinSparkle_wx makes 1 GB lib file

### ISSUE THREAD

**Issue by codecat** [vslavik/winsparkle#166]
I found out this happens because of the `/GL` flag, disabling this for me made the lib file a lot more reasonable to work with. (Down to 50 MB.)

**Comment by vslavik** [comment]
You are welcome to your opinion. However, why you think it's an *issue* or that it matters, when the product is `WinSparkle.dll` and not this intermediate library, and when the result of using it is making the actual product *smaller*, is beyond me.

Closing as non-issue. The use of whole-program optimization in release builds is entirely intentional.

**Comment by codecat** [comment]
I'm linking statically, which is why this is a problem for me in particular. The resulting WinSparkle.lib file is 1 GB in size when this option is enabled.

**Comment by vslavik** [comment]
1. Static linking is unsupported.
2. You seem to misunderstand how static linking work. *It doesn't matter* how large a static library is, because the linker will only pull the bits that actually are used into the (eventual) executable. It's a non-issue.

This will not change. I'm open to a good PR making this configurable in a user-local props file (because why not), but I will not make any changes that make things worse for *standard* use of WinSparkle, as you seem to want (presumably; you didn't actually say what you want in this issue).

**Comment by codecat** [comment]
I understand that in the end when linking it's a non-issue for the resulting binary, but I am storing the lib file so I don't have to build it again, and I'd like to not store a 1 GB file. (Plus, 1 GB is still a pretty big file size to store, not to mention the intermediary .obj files which results to another 1 GB.)

If it's unsupported and you don't think it's a huge problem, that's fine. :) But just thought I'd report it so you're aware that the problem exists, and perhaps others can find this issue and understand what's going on better, too.

Also, do you have numbers on any performance issues that will happen with wx when building w/ or w/o `/GL`? I'd be curious to see, as I believe in another project at work we don't use `/GL` on wx and we haven't ran into any performance troubles there.

**Comment by vslavik** [comment]
> you're aware that the problem exists

Again, I don't consider this a "problem" *at all*. If you disagree, make a non-intrusive PR — but any further *talk* on the subject is just a waste of time for both of us.
