### ISSUE TITLE
Question about UpdateChecker ownership

### ISSUE THREAD

**Issue by justanotherarchuser** [vslavik/winsparkle#189]
Who exactly is an owner of UpdateChecker, for example here:
```
    if ( checkUpdates )
            {
                UpdateChecker *check = new PeriodicUpdateChecker();
                check->Start();
            }
```

Where exactly the memory is released?

**Comment by vslavik** [comment]
This is a bug tracker, not support forum.

`UpdateChecker` is not public API. If you are spelunking inside the code and making changes to it, you should be sufficiently competent to read the existing code and [its documentation](https://github.com/vslavik/winsparkle/blob/c6d90f57459d85e5d26187db26cfd450c4437210/src/threads.h#L110); if you're not, don't mess with the internals.

**Comment by vtronko** [comment]
Sorry, thanks for answer.

**Comment by justanotherarchuser** [comment]
Those are not taken care of in winsparkle cleanup, was unsure if this is a potential memory leak.
Even if I misinterpreted something, it's absolutely not a reason to be such a **dick**

**Comment by vslavik** [comment]
To be clear: not particularly appreciating you wasting my time with your laziness, but nevertheless pointing you in the correct direction, is being a dick.

But entitled demands of support for something freely given, ungratefully wasting my time with *idle* question just because you wasn't "sure" about something and couldn't be bothered doing your homework yourself, or heck, using an automated tool, is not being an ass, right?

I guess I see it differently. Your kind (your only other issue on GitHub appears to be equally, if not more, abusive) and your vocabulary are not welcome here.
