### ISSUE TITLE
Opens file in browser?

### ISSUE THREAD

**Issue by lvandal** [vslavik/winsparkle#223]
Maybe I'm missing something but shouldn't WinSparkle download the update itself and run it?

In https://github.com/vslavik/winsparkle/wiki/User-Experience, it says:

_Install update downloads the new version's installer and launches it._

The download actually occurs in the default browser. My understanding is that it would be like on macOS and the download should occur in-app. I followed the instructions on https://github.com/vslavik/winsparkle/wiki/Basic-Setup and https://github.com/vslavik/winsparkle/wiki/Appcast-Feeds and everything works fine except for downloads.

The file to download is an .exe file generated with InnoSetup.

**Comment by vslavik** [comment]
Please do follow the suggestions here: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

The gist is that nobody else can have any idea about what you do or what you see if you don't *tell* us, in as much detail as possible. You're implicitly assuming that whatever you're doing (of which you say nothing) is normal (it is not) and that everybody else is seeing it (they're not). 

Heck, it's not even clear what is *happening* that you complain about, let alone how you got WinSparkle in that state.

**Comment by lvandal** [comment]
Jeez man thanks for the passive-aggressive response. I was actually going to reply that I just was using the wrong release and that it's working as expected but thanks anyway?

**Comment by vslavik** [comment]
@lvandal I have one more link for you: https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/

> For users: remember when filing an issue, opening a pull request or making a comment on a project to be grateful that people spend their free time to build software you get to use for free. ... Don’t expect anyone to fix your issues or help you if you’re unwilling to dedicate more time to helping yourself than you ask of others. This means reading all the documentation and trying to resolve your own issues before ever asking for any help.

You're acting entitled. You're out of line throwing a tantrum. Put bluntly, you're owed nothing, and certainly not patience with your inconsiderate behavior.

The world doesn't center around you. Maintainers are people too. They have their lives, their time is valuable to them, but yet they spend time responding to issues. By refusing to spend even the minimum time to describe issues coherently, or do what you did a few hours later (which you should have done *before* asking for help; not that "wrong release" would be a thing), you're making it clear that we're lesser people to you whose time is not as valuable as yours.

*Then* you get an unhappy response. Because you're being an entitled jerk.

Maintainers *quit* doing open source over one too many toxic users. Read the eye-opener above. Read http://antirez.com/news/129 about one such high-profile burnout. 

Be considerate in the future. Access to open source projects isn't your God-given right. Actual humans did a lot of work so that you can use WinSparkle and other things freely. You owe them at least being a little considerate in return.
