### ISSUE TITLE
Hi-DPI dialog size issue

### ISSUE THREAD

**Issue by yanone** [vslavik/winsparkle#228]
I’ve recently changed my app to be hi-DPI aware, and noticed a bug.
Upon first app start, the dialog to ask whether updates should be installed automatically, appears for a fraction of a second in normal size, then snaps into 50% size:
<img width="1118" alt="Bildschirmfoto 2021-04-12 um 17 34 34" src="https://user-images.githubusercontent.com/175386/114421502-a6843480-9bb5-11eb-8334-332972b615dc.png">

All other Winsparkle dialogs seem to appear fine. (I haven't checked all of them). But this one, for example, looks fine:
<img width="1131" alt="Bildschirmfoto 2021-04-12 um 17 31 31" src="https://user-images.githubusercontent.com/175386/114421590-be5bb880-9bb5-11eb-9f05-2aaa98ff5ad6.png">

I'm using the latest Winsparkle. Please let me know if I can be of any other help to solve this. (Sadly I have very little experience with Windows development. I work mainly with Macs, and this app is available for both platforms)
Thank you!

**Comment by vslavik** [comment]
> Please let me know if I can be of any other help to solve this.

You can. You can debug it, identify the issue and submit a fix. Or failing that, you can at least provide full reproduction instructions incl. a patch against the included example app and detailed instructions on how to reproduce (incl. versions of OS and other things). 

If I were in your shoes, I would start investigating with the assumption that the issue lies in my code. This looks like you initializing WinSparkle before HiDPI (which is app-global) is in effect. I don't see how could this possibly be specific to a single WinSparkle window.

Regardless of where the bug ultimately is, starting with the assumption that it is *not* in third party code naturally leads to collecting high-quality reproduction steps with accurate and relevant details, should the bug actually be external.

**Comment by yanone** [comment]
> You can. You can debug it, identify the issue and submit a fix.

I’ve seen you write this on other issues. If it only were so simple. I’m so dumb that I’m making an HTML app because I can handle the GUI with it easily instead of using native UI controls.

> This looks like you initializing WinSparkle before HiDPI (which is app-global) is in effect.

See, that was easy. This was all the info I needed. Because you are right, I did that in the wrong order. The timing also makes perfect sense with how the dialog starts big/normal and then suddenly switches to small.

Thanks, that’s all.

**Comment by vslavik** [comment]
> See, that was easy. 
…
> Thanks, that’s all.

You act like an entitled jerk. Knock it off.
