### ISSUE TITLE
Does win sparkle really supports for msi

### ISSUE THREAD

**Issue by dIvYaNshhh** [vslavik/winsparkle#260]
I am facing the issue when installing the update but it never succeeds. As soon as download the install, clicking on `Install Update` just show the installer package information pops up, and if click `Yes` then it's close silently, it never updates any file nor raises any error.

Below is my appcast.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="1.0">
    <channel>
        <title>Title</title>
        <item>
            <title>Version 1.0.0+2</title>
            <sparkle:releaseNotesLink>https://example.com/release-notes/1.0</sparkle:releaseNotesLink>
            <pubDate>Mon, 01 Jan 2023 00:00:00 +0000</pubDate>
            <enclosure url="https://example.com/win/app.msi" type="application/octet-stream" sparkle:dsaSignature="DSA-Signature" length="0" sparkle:version="1.0.0+2" sparkle:installerArguments="/passive" sparkle:os="windows"/>
        </item>
    </channel>
</rss>

```

**Comment by vslavik** [comment]
Please stop filing duplicate issues after I told you clearly that your problem is unrelated to WinSparkle. Please also stop posting drive-by comments to unrelated issues harassing contributors for attention.

If you continue to behave this way, I *will* block you. 

MSI are executables like any others. There's no special treatment needed. You yourself observe that it runs just fine. You have some problem in your non-WinSparkle stuff.

> Below is my appcast.xml
...
> <enclosure url="https://example.com/win/app.msi"

No wonder it doesn't work - that URL is 404. 🤦‍♂️

As a developer, you have no excuse for not knowing how to describe issues reproducibly:  http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
