### ISSUE TITLE
Keeps installing old, cached, version

### ISSUE THREAD

**Issue by kschwan** [vslavik/winsparkle#33]
I'm trying out WinSparkle for a project, and it seems to have been working nicely until now, where I've had the following problem:

On update check, WinSparkle correctly reads the cast and sees that a new version is available. It doesn't, however, download the new version but instead installs the same old version that was downloaded for an earlier update.

Do you have any idea as to why this is happening and how to prevent it?

**Comment by adipose** [comment]
I have duplicated this issue in the latest.  Let me explain what I've found.  The cause of the issue seems to be that I recently updated my appcast server to redirect all http to https.  As a result, winsparkle is getting a 302 (I don't really expect it to handle 302s, and it doesn't).  However, it then moves on and claims to have downloaded an installer, which is an old version from days ago, and no longer on the appcast server.  I discovered that the source is a file that exists in %localappdata%\Microsoft\Windows\INetCache\IE\1B52M05J\<originalfilename>[1].exe.  Because the download failed, or perhaps unrelated to it, it has chosen to use this file as the latest download.  winsparkle must be using an api that depends on the IE caching mechanism.  Perhaps there is a way to disable such caching?

The cached file literally exists nowhere but on my PC.  The server has been scrubbed of it.  Apache has been configured to never cache that file.  Apache has been restarted and the server has been restarted.  I wiresharked the situation and no file is ever downloaded, yet Winsparkle happily tells me it has downloaded the installer.

**Comment by adipose** [comment]
Well, after fixing the https issue, the problem persists.  So maybe it does handle 302s just fine.  Only by clearing my IE cache was I able to get it to recognize the new version.  Now that I tell Apache to not cache that file, maybe it will never happen again.

**Comment by adipose** [comment]
It seems the caching has stopped.  Unfortunately, no one can update currently, because the cache will never expire for them, but at least future caching should be stopped.  Even a clean install of the application will not avoid the cache issue.  I actually have had people install the new version manually, only to have Winsparkle "download" the old one again.  Your suggestion of a different filename for each rev is probably the best solution to that, now that the cached file exists.

**Comment by vslavik** [comment]
@adipose

Assuming that WinInet wouldn't know how to handle redirects is preposterous.

If running your own HTTP server, it's good idea to have some basic grasp of how HTTP caching works and is configured on the server. Significantly missing from all your comments is some information about what cache control headers it actually sends. WinInet or WinSparkle isn't buggy to cache the download, it only ever does that when *your server explicitly asks for the file to be cached.* You *asked* for this to happen, so that should be the first step in your investigation — you must have long expiration times in there.

The above advise to use unique filenames isn't because WinSparkle is buggy, but because it's just a good practice: for large downloads, you typically *want* proxies and CDNs to cache them aggressively, but OTOH you of course *don't* want stale downloads. Also, typical appcasts contain more than one version, which is impossible to do with non-versioned download.

IOW, this issue can be rephrased as "WinSparkle strictly conforms to the HTTP protocol" — not really a *bug*, is that?

Now, the interesting question is **whether it should be as strict**, for both appcast checking and downloads, and I guess the answer is "no" for both. There's definitely no point in keeping a downloaded copy cached in WinInet cache, and it makes sense to always bypass cache when checking the appcast feed, not only when doing it manually (as is the case now). And FWIW, Sparkle bypasses cache.

To complicate matters further, there's a question of *which* caches WinSparkle should bypass. Local one certainly, but should it use `INTERNET_FLAG_PRAGMA_NOCACHE` to bypass proxies? Perhaps not, because proxies are important for traffic reduction. But then it wouldn't help you if misconfigured HTTP server and/or appcast feed if there was a proxy on the way...

**Comment by vslavik** [comment]
The behavior now on trunk probably solves these (mis)configuration issues and IMHO makes sense.

**Comment by adipose** [comment]
> Assuming that WinInet wouldn't know how to handle redirects is preposterous.

Fair enough!  I had experienced other applications (such as Qt) failing to handle redirects, so I made a bad assumption.  Turns out it correctly followed redirects and worked fine.

> If running your own HTTP server, it's good idea to have some basic grasp of how HTTP caching works and is configured on the server. Significantly missing from all your comments is some information about what cache control headers it actually sends. WinInet or WinSparkle isn't buggy to cache the download, it only ever does that when your server explicitly asks for the file to be cached. You asked for this to happen, so that should be the first step in your investigation — you must have long expiration times in there.

I'm pretty comfortable with *disabling* caching on Apache for specific files.  I've never explicitly told Apache to cache anything.

However, I just found that the apache administrator added "ExpiresActive on" to the conf file.  Apparently, if this is enabled, and ExpiresDefault is not, the expiration is "infinite"?  In my case it showed 6 Feb 2106 for the cache headers.

So yes, my web server was misconfigured to cache things a very long time, although the Apache docs are not very clear on what happens if "ExpiresActive" is on without the default being set.  I'll log an issue with them.

I appreciate you making a change to work around misconfigs like mine.  I'm a bit confused when you say Sparkle bypasses cache, though. What was happening for me was it was connecting to the appcast, recognizing there was a new version, saying it was downloading it, but instead it downloaded a *very* old copy.  There were no caching servers or proxies in between (this is connecting to a local apache server on my LAN).  The first thing I did was disable caching for the file, but of course by then it was too late because it was already cached on the client.  As soon as I removed that file from the WinInet, it worked.  Does that square with your understanding of how it was designed to work?

**Comment by adipose** [comment]
I think that 2106 is just a quirk of the firefox cache.  Here were my headers before and after, though.

```
-----old----------
HTTP/1.1 200 OK
Date: Sat, 03 Jun 2017 18:32:25 GMT
Server: Apache/2.4.25 (Win32) OpenSSL/1.0.2k mod_fcgid/2.3.9
Last-Modified: Fri, 02 Jun 2017 22:58:58 GMT
Etag: "7b4f5f-5510219338830"
Accept-Ranges: bytes
Content-Length: 8081247
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: application/x-msdownload


-----new---------
HTTP/1.1 200 OK
Date: Sat, 03 Jun 2017 18:09:00 GMT
Server: Apache/2.4.25 (Win32) OpenSSL/1.0.2k mod_fcgid/2.3.9
Last-Modified: Fri, 02 Jun 2017 22:58:58 GMT
Etag: "7b4f5f-5510219338830"
Accept-Ranges: bytes
Content-Length: 8081247
Cache-Control: max-age=86400
Expires: Sun, 04 Jun 2017 18:09:00 GMT
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: application/x-msdownload
```

**Comment by vslavik** [comment]
@adipose This really isn't the appropriate place to discuss or explain how cache control works in HTTP and/or Apache. Suffice is to say that if your you mananged to serve the same Etag despite modifying the file, as you seem to be saying, that's not on Apache defaults, that's your doing. Please refer to HTTP spec and Apache docs, this really has no relation to WinSparkle.

> I'm a bit confused when you say Sparkle bypasses cache,

Read the README, it says what Sparkle is (hint: not **Win**Sparkle).

**Comment by adipose** [comment]
> This really isn't the appropriate place to discuss or explain how cache control works in HTTP and/or Apache. Suffice is to say that if your you mananged to serve the same Etag despite modifying the file, as you seem to be saying, that's not on Apache defaults, that's your doing. Please refer to HTTP spec and Apache docs, this really has no relation to WinSparkle.

Those were the two sets of headers for the same file, one with the apache "expiredefault" directive on and one without it.  Since earlier you pointed out I didn't supply headers, I wanted to demonstrate what the server was sending.  I'll not post any more about that.

>Read the README, it says what Sparkle is (hint: not WinSparkle).

Oh...right.  Your comment makes sense now.  I was thinking you were abbreviating.
