### ISSUE TITLE
Z ordering wrong

### ISSUE THREAD

**Issue by adipose** [vslavik/winsparkle#41]
In using winsparkle with a qt application, I call win_sparkle_init() in the showEvent() of the main widget.  But, winsparkle pops up behind my application.  I am using Windows 8.1 x64 and Qt 5.3.2.

**Comment by adipose** [comment]
Well, I solved it.  I guess it is a Qt issue.  I have to create a signal to run after the window is loaded in a queued connection, so that the window can fully load before winsparkle runs.  If you try to put it in the showevent, it is still too early.

header:
```c++
virtual void showEvent( QShowEvent * event ) {
  QMainWindow::showEvent(event);
  emit windowLoaded();
...
public signals:
  void initSparkle() {
    win_sparkle_init();
  }
}
```

cpp:
```c++
connect(this, SIGNAL(windowLoaded()), this, SLOT(initSparkle()),Qt::ConnectionType(Qt::QueuedConnection | Qt::UniqueConnection));
```

**Comment by vslavik** [comment]
Thank you for writing down the solution, this is useful documentation.

> I guess it is a Qt issue

I don't think this is a "Qt issue". As is often the case, it makes sense to blame one's own code first. `win_sparkle_init()` documentation says that "You should only call this function when your app is initialized and shows its main window" — exactly because of this, to have a chance to show the window on top. It's not that WinSparkle's window is popping up behind, it's your code that shows a new window immediately after WinSparkle did and hides it.

`QMainWindow::showEvent()` is apparently called when mapping status changed, but right *before* the window is "physically" shown, so delaying it like you did is the correct and recommended approach for Qt (judging from a quick search of SO too). Using a short-lived one-shot timer would be fine in WinSparkle's case too.

**Comment by adipose** [comment]
Right.  I guess when I say it is a Qt issue, I mean there is no signal or event to tell you that your widget has been shown.  Instead you have to catch the "show" event, and queue a signal and hope that it runs after it is actually shown.  Otherwise, there is no good way to know it has "been shown."  Perhaps overriding the draw() method...

**Comment by vslavik** [comment]
> Perhaps overriding the draw() method…

*cringe* Nope, firing a timer or adding an event on the queue as you did are the right things to do. You do have a point that this is a rather… interesting… API design, OTOH it does make some sense: if you want to change the content in reaction to the window being shown, it makes sense like this to avoid flicker.

**Comment by adipose** [comment]
Oh, the showevent function is very useful, it just doesn't solve the problem of notifying that the window has been shown.

The draw() method was a joke :)

**Comment by vslavik** [comment]
May I pick your brains a bit? As a Qt developer, do you find anything distasteful or otherwise bad about doing it like this:
```cxx
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();

    win_sparkle_set_appcast_url("http://winsparkle.org/example/appcast.xml");
    win_sparkle_set_app_details(L"winsparkle.org", L"WinSparkle Qt Example", L"1.0");
    win_sparkle_init();

    int r = a.exec();

    win_sparkle_cleanup();
    return r;
}
```
On one hand, this is certainly simpler, as it doesn't fight against Qt's `showEvent` and it's also more logical in that you want to handle WinSparkle on *app startup*, not when showing some window. On the other hand, Qt programmers are probably used to an idiomatic `main()` implementation?

Why I'm asking: I decided to add a Qt example so that your investigation and this discussion aren't wasted, and would like to know your opinion on what the example should look like, what the best recommendation is. I started using your code at first, but then it occurred to me that this would be another way...

**Comment by adipose** [comment]
I do like the simplicity of that method, but it does break a cardinal Qt rule:

>We recommend that you connect clean-up code to the aboutToQuit() signal, instead of putting it in your application's main() function. This is because, on some platforms the QApplication::exec() call may not return. For example, on the Windows platform, when the user logs off, the system terminates the process after Qt closes all top-level windows. Hence, there is *no guarantee* that the application will have time to exit its event loop and execute code at the end of the main() function, after the QApplication::exec() call.

**Comment by adipose** [comment]
One other comment about your method. For the initialization, it is much cleaner than what I had to do.  And, in my testing, it appears to work.  However, since Qt event processing doesn't "activate" until the .exec() call occurs, I wondered if it might get the z ordering wrong.  It didn't, though. I don't know why (maybe luck), but I believe the show() method should queue the event to show the window, and then the exec() would process that event and make it happen.

I think to be correct, the code should call QApplication::processEvents() after the show() to guarantee the window shows.  This is similar to calling exec(), but it returns after processing the events.

**Comment by vslavik** [comment]
> but it does break a cardinal Qt rule:

That's not relevant here — that matters for important cleanup (e.g. writing user data), not for "only" clean shutdown with proper deallocation to avoid false memory leaks reports etc., which is all that `win_sparkle_cleanup()` does. Besides, your version (from #42) behaves identically in this regard — if  `exec()` never returns, MainWindow destructor isn't called either.

>  I don't know why (maybe luck)

It's not luck, it's because `show()` makes the native window visible immediately — look at the code. Not sure why you'd even expect methods like this to do nothing except putting a command to the queue…

I think I'll use the more complicated events-using code in the example, so that it demonstrates how to do the non-trivial thing, and I'll point to this discussion in a comment in there. Best of both worlds ;)

**Comment by adipose** [comment]
See here for a discussion on show() and processEvents();

http://comments.gmane.org/gmane.comp.lib.qt.user/8003

Maybe not relevant anymore, or maybe it was wrong :)  But I seem to remember having issues with it before.

**Comment by vslavik** [comment]
> Maybe not relevant anymore, or maybe it was wrong :)

Hard to tell, but my guess is that that word "fully" and the talk about `repaint()` is the key. For WinSparkle and for Z-order, "physical" creation of the (native!) window matters, not its content. But *painting* of the window certainly won't happen until the event loop runs on Windows.
