### ISSUE TITLE
Windows positioned off-screen if hosting application has no visible windows

### ISSUE THREAD

**Issue by kenjiuno** [vslavik/winsparkle#46]
UpdateDialog goes out of screen, if no app window available.

P.S. My app has no main window. It stays at tray icon!

--
Here is the previous behavior I have ever seen. 

![olderver](https://cloud.githubusercontent.com/assets/5955540/5833488/3067e694-a197-11e4-8888-4e3d4ff083b3.jpg)

UpdateDialog is located around (34, 22) which will be default behavior of wxTOPLEVEL_EX_DIALOG flag.

--
Applying commits by #22 issue.

![outside](https://cloud.githubusercontent.com/assets/5955540/5833528/91c26540-a197-11e4-9e68-6bdeee3fb7f9.jpg)

UpdateDialog is moved beyond top left corner.

--
I have modified *CenterWindowOnHostApplication* function so that AskPermissionDialog won't get out of screen.

But subsequent UpdateDialog gets out.
Because CenterWindowOnHostApplication function will simply do centering.
UpdateDialog will keep center position against my process's window AskPermissionDialog:

![outside2](https://cloud.githubusercontent.com/assets/5955540/5833550/d4fed8fc-a197-11e4-907c-2f56207b5686.jpg)

--
So I have tweaked around *CenterWindowOnHostApplication* function. UpdateDialog won't get out now.

![moveinside](https://cloud.githubusercontent.com/assets/5955540/5833722/4d0ad368-a199-11e4-9bf8-bda13d39d110.jpg)

--
I have my experimental code for this issue.

However I want to discuss: *centering is ideal for usual cases?*

In my case, I'll disable CenterWindowOnHostApplication and, use it for my customer.
I have worked hard today for this issue, but I began to think whether centering is ideal or not?

**Comment by vslavik** [comment]
> UpdateDialog goes out of screen, if no app window available.

That's undeniably a bug.

> I have modified CenterWindowOnHostApplication function so that AskPermissionDialog won't get out of screen.

So where's the PR? And does it work in multi-display case?

> UpdateDialog will keep center position against my process's window AskPermissionDialog:

Sorry, but this begs a question: what the heck are you *doing?* I appreciate that you previously found a problem in this corner case, but let's make one thing clear: *this is not normal*. It seems you are *intentionally* making both of these windows appear (not having the user do it explicitly)? Why? There's a reason why WinSparkle asks for permission first: you *shouldn't do the checks* if the user disagrees. And the above screenshot is pretty blatant in-your-face "I'll ignore your answer anyway"...

> I have worked hard today for this issue, but I began to think whether centering is ideal or not?

Perhaps you should actually spend some time arguing or at least *explaining* your position, disagreement or whatever it is you're trying to communicate. Because right now all I can tell you is that well, *obviously* I considered it a good idea (see also #22, #34, #37). So?

**Comment by kenjiuno** [comment]
Hi.

I'm sorry for confusing so much... I have no intention to offend you.


> blatant in-your-face "I'll ignore your answer anyway"...

Sorry. I mean I have limited period to fix this issue for my customer. So, I'll simply disable it for now.

I'll try to provide or consider incoming ideas in the future.

> So where's the PR? And does it work in multi-display case?

I'll push a pr in the future. It won't consider multi-display case. I need more research for other cases which is not covering this issue.

> There's a reason why WinSparkle asks for permission first

Yes, its part include 2 problems:
- UpdateDialog extends vertically if there is an available update. It causes get out of screen probably.
- AskPermission can be treated as your app main window. If your main app window is small and located at top-left corner or bottom-right corner... It will get out.

kenji uno

**Comment by vslavik** [comment]
> I'm sorry for confusing so much... I have no intention to offend you.
>
> > blatant in-your-face "I'll ignore your answer anyway"…
> Sorry.

No, you misunderstand. You are *doing this to your users*. You are asking them for permission to do something and without waiting for their answer, *you do it anyway*. That's terrible.

Again, why are you doing this? And also, *how* are you doing this? Because this is *not* normal WinSparkle behavior. It seems to be that you are calling `win_sparkle_check_update_with_ui()` without user interaction to trigger it — don't do that.

> It won't consider multi-display case.

The point was that any code included in WinSparkle absolutely has to… I'll have a look myself, then.

**Comment by kenjiuno** [comment]
Hmm.

I admit that my one is very rare case.

But I want to believe it is not an abnormal case... My app has no main window. It stays at tray icon.

Here is my pseudo code using WinSparkle.
```
            try {
                WinSparkle.win_sparkle_set_appcast_url(AppcastUrl);
				...
                WinSparkle.win_sparkle_init();
                if (auto)
                    WinSparkle.win_sparkle_check_update_without_ui();
                else
                    WinSparkle.win_sparkle_check_update_with_ui();
            }
            catch (BadImageFormatException) { }
```

win_sparkle_init will show AskForPermission, if user has never answered.

auto is True, and then call *win_sparkle_check_update_without_ui*, because the code is called from startup code. It may display UpdateDialog, if update is avail.

**Comment by kenjiuno** [comment]
I'm sorry.

Is the main problem that I didn't mention "My app has no main window. It stays at tray icon." at first post?

**Comment by vslavik** [comment]
This code is bad:
1. You should *never* call `win_sparkle_check_update_with_ui()` automatically - only call it if the user *explicitly asks to check for updates*.
2. You're just duplicating what `win_sparkle_init()` does.

This is what you should do instead:
```cxx
win_sparkle_set_appcast_url(AppcastUrl);
win_sparkle_set_automatic_check_for_updates(auto);
win_sparkle_init();
```
That's the clean way to do what you apparently intended to do.

P.S. All this is explained in `winsparkle.h` documentation…
P.P.S. For crying out loud, don't silently catch & trash serious exceptions like that!

**Comment by kenjiuno** [comment]
Hi.

Thanks for code advising. I'll try it. And I'll check docs written at winsparkle.h later.



> don't silently catch & trash serious exceptions like that!

Oh, I have forgotten about that catch for long time... Ok, I'll check it too.

**Comment by kenjiuno** [comment]
Hi.

I'll talk about how I have encountered this issue in my product...

I had done **rebase** my private branch up to latest master's head. If I didn't do rebase, I wouldn't have noticed about this issue (windows positioned off-screen).

And, I have noticed this issue when I saw an update screen of next version. lol.
So, I have allowed to distribute number of copies of my developing app having this issue.
It is just my fault. It is not the point of this issue.

The point is the timing it appears:
If a developer do rebase his branch up to latest head, he will notice this problem when he will publish one after the next version.
Of course, it will not occur on good case like having main window.

This is the main reason I want to report this issue, and want to supply pr for this issue.
Perhaps this can be very officious.

**Comment by vslavik** [comment]
> This is the main reason I want to report this issue, 

As I said, this is clearly a bug. Nobody disputes that — to be frank, there's really no reason to continue babbling on the subject. The centering bug is clear and unambiguous. Pretty much everything else in this issue is just irrelevant noise, though :-(

> and want to supply pr for this issue.

You also stated that you will ignore the need to do it correctly for multi-monitor uses. So there's really no point.

This is a simple bug to fix and I will fix it soon, don't worry about it.

**Comment by kenjiuno** [comment]
Hi.

Thank you for fixing of this issue. I have tested the latest c90ddf39bf02aeae7d8ed140c32f8d5c90b9ae7b, and there is no problem in my case now.

I have erased *win_sparkle_check_update_xxx* call at startup, and there is only one window (AskPermission or UpdateDialog) simultaneously now.
