### ISSUE TITLE
error: LNK1104: cannot open file 'yacc.obj'

### ISSUE THREAD

**Issue by fanntone** [vslavik/winsparkle#47]
I 'd download and build your example project show:
":error: LNK1104: cannot open file 'yacc.obj'"

my system: windows8.1+Qt 5.4

**Comment by vslavik** [comment]
There's *no mention* of "yacc" anywhere in the winsparkle repository (as you could have trivially verified). Whatever the problem is, with whatever it is that you're using (you don't bother to tell), it's not a WinSparkle problem, but a problem with your tools. My guess: you're using Qt's known-to-be-broken Visual Studio addin?

If you find anything worth improving in `examples/qt`, please contribute a pull request. I'm not a Qt user and while I was (barely) able to build with Qt Creator, that's it.

**Comment by fanntone** [comment]
Thank you~
