### ISSUE TITLE
update check error

### ISSUE THREAD

**Issue by fanntone** [vslavik/winsparkle#48]
It's my code:
    /* initialize WinSparkle as soon as the app itself is initialized, right
       before entering the event loop: */
	win_sparkle_set_appcast_url("http://googledrive.com/host/0B7uLD-nJke_ANlQ1Q1ZGODY3dmM/mytest.xml");
    win_sparkle_init();

First start winsparkle Im use version="1.5.4 " to install Poedit, and second start Poedit I agree check automatically done.
1. Then I 'd update mytest.xml file to version="1.5.7".
2. Start winsparkle happend:
![untitled](https://cloud.githubusercontent.com/assets/8188050/5852963/33b14c24-a259-11e4-8dc3-2ff071a4a845.png)

I just add one line code in your example.

**Comment by fanntone** [comment]
I'd start Poedit app again , it's seem not to update auotomatically.

**Comment by vslavik** [comment]
I don't know what you're complaining about here, it's not comprehensible unfortunately, but everything seems to be OK. "1.0" is version from the example — *it is correct that it shows this version.*

You seem to think that this *WinSparkle example* is the unrelated Poedit application. It is not. The dummy release notes in the screenshot *even tell you they are not real*. The example shows you how WinSparkle works, it doesn't fully update itself (it very well *can't*, because you don't even have the example installed).

(As an aside, please try to improve your issues reporting — this issue isn't making any sense, you don't even describe what you think the problem *is*, let alone doing it succinctly, clearly and descriptively (same issue as with #47, really). Spend some time trying to understand things at least a bit, instead of immediately filing incomprehensible issues — chances are that in the process of investigating the issue so that you can describe it *well*, you're understand things better.)

**Comment by fanntone** [comment]
I'm sorry my English skills are not good enough.

**Comment by vslavik** [comment]
> I'm sorry my English skills are not good enough.

This is not a matter of English skills, your English is understandable and just fine. It's the *content* of what you're writing that is severely lacking in clarity, preciseness, specificity and detail; it's your thought process and attitude behind it that are the issue. Don't blame any of that on "English skills" — sorry, but that's just a lazy excuse.
