### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by kkuday** [vslavik/winsparkle#53]

**Comment by kkuday** [comment]
Hello 

I used win sparkle for my windows application , it' s worked fine for me .  I am trying to build win sparkle source code  I unable to build it  , so please provide some documentation  clearly , how to build source code of win sparkle.   I building it in my visual studio 2012 express edition .

**Comment by vslavik** [comment]
Documentation on how to build WinSparkle is, of course, included in the file `README.md` — thus named because *you should read it*. This being a library for developers, the instructions expect certain minimal level of competence, but that’s about it, there’s nothing you could possibly have trouble following, whatever your mysterious problems are. My recommendation: read the readme, pay attention when doing so, and follow the directions. Apply common sense to any unexpected issues with your compiler (you’re a developer, that’s what you *do*, isn’t it?).

Please also note that the issue tracker is intended for *tracking issues* — [good bugreports](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) of actual issues, PRs or [at-least-a-bit-researched](http://www.catb.org/esr/faqs/smart-questions.html) and [well-formulated](http://stackoverflow.com/help/how-to-ask) questions. Feel free to create such issues (after reading those three links), but please refrain from posting more “Hello”s like this or #52.
