### ISSUE TITLE
"Skip this version" not respected by win_sparkle_check_update_without_ui() 

### ISSUE THREAD

**Issue by ronnieviegas** [vslavik/winsparkle#64]
Thanks for Winsparkle. 
We integrated your framework with our app and it works well on all Windows 8 & 8.1 systems except a few users on Windows 7. All reports of this issue have been on Windows 7 systems. Every time they skip a minor update, on next launch it pops up dialog saying new update is available for same version.
Could this be an issue with appcast xml ?

**Comment by vslavik** [comment]
> Could this be an issue with appcast xml ?

The only explanation I can see if you keep changing the version in the appcast. As you can see for yourself, only the appcast version is relevant: [here](https://github.com/vslavik/winsparkle/blob/386be15c99911d7e56ed243c1b45f781cd83d309/src/updatechecker.cpp#L266), [here](https://github.com/vslavik/winsparkle/blob/f4167e19b5b95cc2de1a9abcf219f4e95ec9bab7/src/ui.cpp#L602) and [here](https://github.com/vslavik/winsparkle/blob/386be15c99911d7e56ed243c1b45f781cd83d309/src/updatechecker.cpp#L251).

Well, either that or something or somebody is actively deleting WinSparkle’s registry entries.

If you believe there’s a bug in WinSparkle, please provide a complete, *reproducible* test case, incl. the feed and detailed instructions on how to reproduce.

**Comment by ronnieviegas** [comment]
Actually I am able to reproduce it on Windows 8.1 too.
I created a sample project and uploaded it on drive
https://drive.google.com/a/splashdata.com/file/d/0B6ECcJRY3krPclNtRmdocXVCWUE/view?usp=sharing

**Comment by vslavik** [comment]
Did you verify its not a problem with your feed?

Since you have everything set up, why not go the small extra step and actually debug it yourself, by pitting not break points at the locations I pointed you to? Or at least provide a minimalistic patch for the WinSparkle example to reproduce it without having to setup and build whatnot else (if it's WinSparkle issue, it must surely be reproducible in the example too)?

**Comment by ronnieviegas** [comment]
The problem was that I had added a call to "win_sparkle_check_update_without_ui();" which was like doing a manual check on every launch.

**Comment by vslavik** [comment]
Out of curiosity, what mislead you into thinking you need to call anything except `win_sparkle_init()`? This is surprisingly common, I'd like to improve the docs if there's anything to improve...

I'm also reopening this ticket, because it shows behavior that is to me surprising or at least not *obviously* correct: it's clear that `win_sparkle_init()` needs to respect "skip this version". It's equally clear that `win_sparkle_check_update_with_ui()` should not (used for explicit check by the user, consistent with Sparkle.framework). But it isn't obvious to me which way should `win_sparkle_check_update_without_ui()` work.

In any case, at the very least their docstrings need to describe their behavior in this regard (neither currently docs).

**Comment by ronnieviegas** [comment]
I think its the word "init" in `win_sparkle_init()` that made me think it only initializes and does nothing else and that more needs to be done to start an auto check. Also half look at the code sample and winsparkle.h file contributed towards this misunderstanding, so its not entirely the fault of function name. winsparkle.h clearly states that it `proceeds to perform the check`.

Also renaming `win_sparkle_check_update_without_ui()` to `win_sparkle_force_check_update_without_ui() ` will give us a hint that it overrides all ignore flags. Right now the name doesn't give away that its to be used only for forcing a check for update. 

Normally I bother to check the documentation for a method when it has parameters and/or return values, otherwise I depend on the method name to explain itself.

BTW simple & solid framework. Good job.

**Comment by vslavik** [comment]
> Normally I bother to check the documentation for a method when it has parameters and/or return values, otherwise I depend on the method name to explain itself.

😱 You *really* should reconsider that approach. Case in point: time wasted by you and me both just because you didn’t RTFM…

**Comment by ronnieviegas** [comment]
Yes, I agree, I turn dyslexic when it comes to reading documentation. I need to work on it

**Comment by vslavik** [comment]
Turns out that the worst part about this issue is that it is bogus to begin with — `win_sparkle_check_update_without_ui()` *does* in fact respect “Skip this version” since 7de9a8d0. You must have been using an ancient version of WinSparkle. (Bug reporting 101: always always always try to use the latest sources first.)

My mistake for trusting the info here blindly and committing e22888e, which now had to be corrected in 00fbcfe0.
