### ISSUE TITLE
Include all previous release notes in the dialog up to the current version

### ISSUE THREAD

**Issue by AhmedBM** [vslavik/winsparkle#67]
When the sparkle dialog is shown, only the current release notes are shown. We should be showing all release notes from the next build after the currently running up to the currently most recent build.

**Comment by vslavik** [comment]
Can't do that, for two reasons:

(1) One of WinSparkle's goals is compatibility with Sparkle and Sparkle doesn't do that either.

(2) This is ultimately the *server's* responsibility. WinSparkle (as, again, Sparkle) includes app name and version in the User-Agent with all requests and e.g. [Poedit's](http://poedit.net) feed server does exactly what you want, because my preferences are similar to yours in this regard.

But you can't force this preferences on everybody. `<description>` is free-form by spec and it's not always obvious even *how* to put them together from multiple items, let alone *if* it should be done in the first place. Some people (like you, I'm guessing) put a version heading there with a bullet list. Some use paragraphs of text. Some group items logically, with features first and bugfixes last. Some repeat major changes in the description of point releases, some don't. Some use simply CSS, some use complex styling that prevents you from just concatenating the notes (and of course, they may use *different* CSS too). When you release a major new version 5.0, some trivial small bugfix in 4.8.42 probably isn't of much interest. When you publish *beta versions*, you probably don't want to show them to people that only use stable versions. And so on.

That is to say: it's complicated. And it's the server's job to do it the way you like it.

**Comment by AhmedBM** [comment]
Ok good point, i noticed a few apps that do this thats why i was under the impression that Sparkle framework provided it and not the feed server. Ill look into building a feed server similarly to Poedit's that does this, thanks for the tip :)
