### ISSUE TITLE
Check for updates and install if availble

### ISSUE THREAD

**Issue by statico** [vslavik/winsparkle#76]
Hi @vslavik,

We need to strongly urge users into always using the latest version of our application. I'd like a function that will check for updates and install them if available. The UI should be present, and the main thread should be notified if the user cancels the download. I've implemented the functionality in sparkle (see https://github.com/sparkle-project/Sparkle/pull/620) and I'd like to implement its counterpart in winsparkle.

How would you suggest I begin? Some possibilities include:

- An entry point function called `win_sparkle_check_and_install_with_ui()`
- An `UpdateChecker` subclass which calls a new static method on UI, such as `UI::InstallUpdate()`.

Thoughts?

**Comment by vslavik** [comment]
> How would you suggest I begin?

Not filing issues for what aren’t *issues* but open-ended questions would be nice ;-) (It’s not like my contact info is secret…)

More to the point, I’m not even sure what you’re asking for:

> An entry point function called win_sparkle_check_and_install_with_ui()

Well, *obviously* you’ll have to have a new public function, no? Notice though that the `_with_ui` suffix means “with UI being shown *immediately*” (see the docs), so probably not what you want. Unless I misunderstand your goal.

> An UpdateChecker subclass which calls a new static method on UI, such as UI::InstallUpdate().

Clearly you’ll need to do some code changes to implement it too, so it’s not either-or, but I can’t tell you off-hand what they’ll need to be, in part because it’s not entirely clear what the *exact* behavior you want is and how it differs from `win_sparkle_check_update_without_ui()` — or for that matter from unconditionally calling `win_sparkle_set_automatic_check_for_updates(1)`. It’s as always: read the code, understand what needs to be changed, change it. FWIW, if your intention is to change UI flow, `UpdateChecker` isn’t really related to that, but yes, you’d probably need to add some indicator methods to it (such as `bool InstallAutomatically()`? — again, not entirely clear what you want in the first place) that the UI code in `UI` class uses to adjust its behavior.

Perhaps you should just start and make a work-in-progress PR when you need more specific review/advice?

**Comment by statico** [comment]
Superseded by https://github.com/vslavik/winsparkle/pull/77
