### ISSUE TITLE
Error building with VS2015

### ISSUE THREAD

**Issue by steronydh** [vslavik/winsparkle#78]
I have followed the instructions to download the source from Github along with the dependencies, but when I compile it I get this error:

1><path>\winsparkle\WinSparkle.targets(19,5): error MSB3073: The command "packages\Gettext.Tools.0.19.4\tools\msgfmt.exe -c -c -o "translations\bg.mo" translations\bg.po" exited with code 3.

**Comment by vslavik** [comment]
You must have, for whatever reason, disabled NuGet integration in Visual Studio and must be missing `packages\Gettext.Tools.0.19.4` content because of that.

If you believe that’s not the case, investigate (checking if a comment that is quoted to you runs from command prompt is not a rocket science), describe what the actual problem is, ideally with a PR to go with it. But missing NuGet restore seems to be the most likely cause.
