### ISSUE TITLE
Dependencies and suggestions

### ISSUE THREAD

**Issue by boatschl** [vslavik/winsparkle#83]
So I like the library but ran into a few issues I want to list here:

1. The source is missing some dependencies: "Cannot open source file: 'wxWidgets\src\msw\*** ". Is there any way to download those seperately? I need to recompile the project because to use it I would need to change some of the update check logic, localise the dialog strings and most importantly remove the "only check once per hour" restriction since right now I have to set the registry time stamp to 0 at app start.
2. The windows binaries download link seems to be outdated. The header file included is different from the one in the source directory (missing error callback).
3. There is a callback for error handling but no information abour what happend. Any possibility to add like a descriptive string/error enum code etc?
4. In the RSS XML file only the topmost <item> is used (so the newest version must be inserted on top or must replace the old entry). It would be way more convenient to scan all items and return the latest.
5. The sparcle:version is only tracked within the <enclosure>. The OS X documentation states: "If you want to provide a download link, instead of having Sparkle download and install the update itself, you can omit the <enclosure> tag and add <sparkle:version> and <link> tags". Adding this feature would be a great addition.

**Comment by vslavik** [comment]
> The source is missing some dependencies:

The source code is not missing anything, but you’re ignoring the README file, which is there to be read and which explains to you how to use git to checkout the tree.

> The windows binaries download link seems to be outdated. 

Yes, a git repository contains changes since the last release and they will go into the next release. That’s the way of development life.

> Any possibility to add like a descriptive string/error enum code etc?

Sure. I’m eagerly awaiting your PR.

> It would be way more convenient to scan all items and return the latest.

It wouldn’t for the implementation. You are, of course, welcome to submit a PR that does as you wish, but FWIW, this is just fine for 99.99999999% of feeds out there (basically, the rest of the world).

> The sparcle:version is only tracked within the . The OS X documentation states: "If you want to provide a download link, instead of having Sparkle download and install the update itself, you can omit the tag and add sparkle:version and tags". Adding this feature would be a great addition.

I have no idea what you meant by this, you seem to have accidentally deleted some key words. In any case, you are welcome to submit a PR.

This is an Open Source project: if you don’t like something, sit down and fix it instead of idly complaining.

(Closing because this isn’t an actionable issue (or even an ugly assorted bag of completely unrelated actionable issues.)

**Comment by boatschl** [comment]
Don't be so mean, that's why it is called a suggestion not a demand. You will get your PR, do you prefer error codes (enum) or const char* strings with a descriptive name as parameter?

In the last section there is indeed something missing, my bad. I meant to say that the sparkle:version is only tracked within an 'enclosure' as attribute, not as seperate entry in 'item', thus the reference to the OS X docu. Therefore if you do not provide a download enclosure one might want to display the download link provided instead. Does that make more sense?

**Comment by vslavik** [comment]
> Don't be so mean, 

I’m not “mean”, but *you are* very inconsiderate when you waste others’ time only because you couldn’t be bothered to spend one minute reading the README first.

> that's why it is called a suggestion not a demand

Suggestions (and particularly poorly researched ones) are mostly worthless.  Well-described bugs are useful, well-reasoned detailed feature requests are useful, good code is useful. Vague “suggestions”? Not so much.

> In the last section there is indeed something missing, my bad. I meant to say that the sparkle:version is only tracked within an 'enclosure' as attribute, not as seperate entry in 'item', thus the reference to the OS X docu. Therefore if you do not provide a download enclosure one might want to display the download link provided instead. Does that make more sense?

That would be an example of a very poorly researched “suggestion” that only wastes everybody’s time. #40 already addressed it (observe how it’s a PR, too, not a “suggestion”).
