### ISSUE TITLE
WinSparkle crash in sleep mode

### ISSUE THREAD

**Issue by Houd1ny** [vslavik/winsparkle#86]
For some users win sparkle crash.
I can`t reproduce this on my own.
But I have crash reports from users.
They are attached.
[1.txt](https://github.com/vslavik/winsparkle/files/106861/1.txt)
[2.txt](https://github.com/vslavik/winsparkle/files/106863/2.txt)
[3.txt](https://github.com/vslavik/winsparkle/files/106889/3.txt)

**Comment by Houd1ny** [comment]
I think one fix is to remove 
rethrow of exception  in UpdateChecker and UpdateDownloader
because they run in different spread CATCH_ALL_EXCEPTIONS can`t catch them.

**Comment by vslavik** [comment]
Thanks!

> run in different spread

I have no idea what you mean by that, sorry — can you please be more specific? You have the code at your disposal, you know, you could actually show the suggested code and some me some time, since you clearly already investigated this a bit…

But generally speaking, no, silently loosing errors is *most definitely* no the right thing to do. Making sure everything is caught and logged is.

**Comment by Houd1ny** [comment]
@vslavik  sorry I meant thread not spread.

**Comment by Houd1ny** [comment]
@vslavik  as I understand you run UpdateDownloader and UpdateChecker  in different thread asynchronously. And because they are in different thread 
there are no one that can catch this rethrow
catch ( ... )
    {
        UI::NotifyUpdateError();
	throw;
    }

**Comment by vslavik** [comment]
What does "in sleep mode" in the title mean? Presumably it's about putting the computer into sleep while the host app is… doing what, exactly? Just being? Checking for updates at the moment? Actively downloading? Just having some WinSparkle UI shown but not doing anything?

**Comment by Houd1ny** [comment]
@vslavik  We have found what was the problem. Our user generated crash reports from winsparkle, but app in reality did n`t crash. That was exceptions in win sparkle. I think that was because they was unhandled and in different thread. We fixed this just filtering exception that do no cause crash. I close this issue
Thank you for your time.

**Comment by vslavik** [comment]
Kindly leave the decision of closing to me. 

It was obvious from the very beginning that this was an uncaught exception. Uncaught exceptions are bad. Bad things should be fixed.

**Comment by vslavik** [comment]
Upon code review, this issue was indeed bogus: *all* exceptions thrown in threads *are* caught correctly. So your crash reported wasn't misreporting *uncaught* exceptions (it would be right to report that!), but was misreporting *any* thrown — and later caught — exceptions.

You were right to close the issue, I just didn't understand what you were saying then (I do now).
