### ISSUE TITLE
WinSparkle crashes after having registered callbacks

### ISSUE THREAD

**Issue by ThomasBarnekow** [vslavik/winsparkle#89]
I'm running into a weird error when trying to use the CanShutdownCallback and ShutdownRequestCallback in a VSTO Word Add-in. Let me try to explain the situation.

I've built my own WinSparkle Wrapper class for .NET and tested that using a Windows Forms application. That worked nicely, even with the callbacks mentioned above. 

I then used the same wrapper and general approach in a VSTO Word Add-in. "General approach" means that certain things are done in different places in such an Add-in. The strange thing that happens with the VSTO Add-in, though, is that the following exception is thrown:

```
An unhandled exception of type 'System.NullReferenceException' occurred in Unknown Module.

Additional information: Object reference not set to an instance of an object.
```

This only happens when clicking the "Install update" button of the "Software Update" dialog once it says "Ready to install." in conjunction with the `CanShutdownCallback` having been registered using the `SetCanShutdownCallback` method. Here's the signature:

```
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate int CanShutdownCallback();

[DllImport("WinSparkle.dll", EntryPoint = "win_sparkle_set_can_shutdown_callback", CallingConvention = CallingConvention.Cdecl)]
public static extern void SetCanShutdownCallback([MarshalAs(UnmanagedType.FunctionPtr)] CanShutdownCallback callback);
```

If the callback is not set, everything works fine. As soon as it is set, the exception will get thrown.

I'm using the WinSparkle release version 0.4.

**Comment by Marginal** [comment]
See point 4 in [this MSDN doc](https://msdn.microsoft.com/en-us/library/d186xcf0%28VS.71%29.aspx).

(Can't say for sure that's your problem, but I [ran into](https://github.com/Marginal/EDMarketConnector/blob/master/update.py#L90) this problem in Python).

**Comment by ThomasBarnekow** [comment]
@Marginal Thanks, that was exactly the right hint. Making sure those callbacks weren't garbage-collected solved the issue.

The interesting thing is that that didn't happen at all with my Windows Forms application.

**Comment by vslavik** [comment]
Please always make sure you try with the latest code first. 0.4 is *old*. Consider changing your default assumption from “it’s the library I use” to “it’s my code” as well. In this case, you have a situation where:
 1. You use your own bindings.
 2. The crash happens only when you make WinSparkle *call your code*.
 3. The error is obviously a .NET runtime one *which can’t possibly originate* in WinSparkle’s *native* C++ code.

A reasonable conclusion from that would be that there’s some bug in your code, not that “WinSparkle crashes”. Closing as not-a-bug, because I don’t think there’s anything to be done here. It does serve as a reminder to make sure that #73 keeps references around, so let’s call that a successful issue overall ;)

(I’m impressed by @Marginal’s [psychic powers](https://blogs.msdn.microsoft.com/oldnewthing/20050321-00/?p=36123/), by the way, that’s one hell of zero-information debugging right there.)

**Comment by ThomasBarnekow** [comment]
Before closing this, let me say the following:

- WinSparkle is really helpful. @vslavik thanks a lot for producing and maintaining it!
- My issue had nothing to do with WinSparkle itself. This is a .NET issue. The C# language now pretty much hides the fact that a Delegate object is created (and possibly garbage-collected). Thus, garbage collection is not the first thing you think about (so @Marginal's hint was spot-on).

After having produced my wrapper, I saw that there is a pull request regarding a .NET wrapper which I would have happily used. However, I've noted that the callback functions (e.g., CanShutdownCallback) are declared using `CallingConvention.StdCall` calling convention rather than `CallingConvention.Cdecl`. Here's the WinSparkle declaration:
```
typedef int (__cdecl *win_sparkle_can_shutdown_callback_t)();
```
And here's the corresponding C# code from the PR:
```
[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate bool CanShutdownCallback();
```
Not sure whether that is a problem.

**Comment by ThomasBarnekow** [comment]
@vslavik Just saw that you have already closed it before I posted my last comment.

Let me say that I always consider the possibility that "it's my code" first. However, after having tested a good number of things (and a good deal of searching on the Internet), I opened that issue. And that lead to that spot-on hint which helped solve my problem. And while WinSparkle turned out to be "innocent", the thought that WinSparkle might (!) be part of the problem in this scenario is fair, isn't it? Thus, there's no reason to become defensive.

It could make sense to amend the documentation, adding a section on potential issues like mine. WinSparkle users are likely to run into this again. Also, further examples might help and I'd be willing to share an example showing how to use WinSparkle in a VSTO add-in. 

By the way, I've already amended the Appcast Feeds section in the Wiki because it took quite a while to find out how to correctly produce that Appcast XML file. While I have been using XML for software development since 1998 or so, I had not yet worked with RSS. Again, other WinSparkle users might run into the same issue, so I thought it would be helpful to provide some documentation.

I've seen that WinSparkle 0.4 is old. Therefore, I also cloned the repo (last weekend). But the code didn't compile (using Visual Studio 2013). So I reverted back to using 0.4. The question is whether you could produce a newer release for us to download (because the repo and especially the submodule(s) are so huge).

**Comment by vslavik** [comment]
> Let me say that I always consider the possibility that "it's my code” first

I meant it more like “comprehensibly rule out, which happens to gather useful evidence about the bug”…

> the thought that WinSparkle might (!) be part of the problem in this scenario is fair, isn't it?

No, it really isn’t (and pointing out a flaw in your reasoning isn’t “defensive”!). Fact 3 above (getting a *.NET* exception) pretty much proves it can’t be in WinSparkle code. 

> It could make sense to amend the documentation, adding a section on potential issues like mine. 

I don’t think it does, in this case. This is unrelated to WinSparkle, it’s a matter of understanding how .NET runtime (i.e. the language you use WinSparkle) works and that you must hold references to things you want to use from references-unaware native code.

What *does* make more sense is to get my act together, finish reviewing and fixing the .NET bindings and merge them a.s.a.p., so that people can use the official thing. This will be moot then.

> But the code didn't compile (using Visual Studio 2013)

It won’t surprise you that I don’t find a “it doesn’t compile, let’s go shopping” reaction reasonable. Current `master` [very much does compile](https://ci.appveyor.com/project/vslavik/winsparkle), of course (with VS2013 no less), so I can only assume the issue was that you didn’t follow the README for checking out.

> The question is whether you could produce a newer release for us to download

I could, and I will, once things I want in it are there. I didn’t consider it high priority, because the one thing developers, WinSparkle’s target audience, are supposed to be good at is compiling things. And I did make sure that the build process isn’t arcane, but very basic: checkout from git (OK, with submodules), use the solution.

**Comment by ThomasBarnekow** [comment]
@vslavik If you want WinSparkle users to be successful in using WinSparkle in various use cases, it does make sense to point out certain pitfalls they might encounter. I would not expect most .NET developers to regularly work with native DLLs, let alone callbacks. Not everybody is experienced with lower-level .NET runtime and interoperability issues.

WinSparkle certainly compiles in most situations, e.g., on your machine and on AppVeyor. It does not compile, however, if the solution path has blanks in it (which I found out after some analysis). This is the case, for example, if your WinSparkle project folder sits in the Visual Studio default location for projects which happens to have "Visual Studio 2013" in it (if you are using Visual Studio 2013).
