### ISSUE TITLE
Feature Request:  Disable UI

### ISSUE THREAD

**Issue by henrita** [vslavik/winsparkle#95]
I don't have any complaints on the design of the winsparkle popup per se, but its look-and-feel does clash with our own UI.  We were looking for a way to disable the popup.  I was hoping to be able to do one of these instead:
1. Get a call-back that an update is available so we can display our own popup.
2. Set an 'always update' flag so that the popup is skipped and it just goes ahead with the download.

**Comment by vslavik** [comment]
I have no plans to do this — goes against the whole point of WinSparkle.

If you are using non-standard UI (otherwise the standard UI WinSparkle uses wouldn't "clash") and have such special needs to satisfy, you really shouldn't be posting "feature requests" — nobody is going to spend hours of days of time doing something useful only for you. That UI code is pretty centralized, it would be possible to make changes to the (internal, C++) API to make it possible to plug in different UI, so if you really want to make that happen, you can either implement it and submit a PR (I gladly accept all quality contributions) or fund the development.

Closing because there's no point in keeping the issue open unless somebody else commits to actually implementing it.

**Comment by henrita** [comment]
I took the time to document an issue we had.  I don't think I'll do that with WinSparkle another time.  We had actually thought about contributing the change, but if you feel that way about it, I guess we'll do our own thing.

**Comment by vslavik** [comment]
You didn't document, you made a request — don't blame me for your own phrasing which *did* come off quite entitled. You also made a request for something that WinSparkle quite simply isn't meant to do, as I tried to explain to you.

Honestly, yes, if you don't care for WinSparkle's UI, there's not much *else* left in there, and I think you would indeed be better off using some small headless code instead — it's not like the non-UI part of WinSparkle, i.e. a little bit of appcast parsing code, is rocket science.

**Comment by henrita** [comment]
Fair enough.
