### ISSUE TITLE
http/https authentication

### ISSUE THREAD

**Issue by mehdilauters** [vslavik/winsparkle#96]
It would be useful to provide a basic http authentication, by setting a username and a password for all network queries

**Comment by vslavik** [comment]
Since this would be useful *for you* (because it's not all that useful in normal circumstances), that means *you* are the best person to implement it. Do it, submit a PR, and I'll gladly merge it. That's how Open Source works. But expecting that somebody else does it for you (because code doesn't just magically materialize on its own) is a bit entitled.

**Comment by mehdilauters** [comment]
Yes it would be useful for us, at least, but we managed a way to avoid it.
This issue was not an attack just a feedback for a small "missing" feature, and before opening it I had a check to the source code in order to maybe provide a merge request.
We maybe will have to implement it and this issue was a way to follow it.
By the way, if we really need it, we will do it and share it.
Regards

**Comment by vslavik** [comment]
> merge request

There was no merge request…

> and this issue was a way to follow it.

No, let's be honest here: it really wasn't, that's not how you worded it at all.
