### ISSUE TITLE
Use native Windows API instead of wxWidgets?

### ISSUE THREAD

**Issue by wxiaoguang** [vslavik/winsparkle#97]
wxWidgets is too large ...

**Comment by vslavik** [comment]
Wow… you are unbelievable. You contribute no code or anything of value (judging from your GitHub profile, that's the way you roll, not just WinSparkle), yet you have the nerve to *complain* — and about something that is totally inconsequential in 2016 no less. Ungrateful entitled people like you are [why developers burn out on doing Open Source](http://hueniverse.com/2016/01/26/how-to-use-open-source-and-shut-the-fuck-up-at-the-same-time/). 

If you don't like something about WinSparkle, sit down *and do something about it*. wx would certainly appreciate your *actual* efforts to cut it down. And cut the lame excuses about how you'd love to, but sadly  "don't know C++, wx or whatever" — the concept is called *learning new things*. But you won't, of course, you'd rather waste everybody's time by creating stupid and totally clueless issues like this one. And if by some miracle you actually touch the  code, you'll quickly realize how ill-advised the whole idea was.

Because here's newsflash for you: there are actual *reasons* for this tradeoff and they aren't, surprising as it may seem to you, my complete and utter incompetence. So if you expected me to see the error of my ways upon seeing your issue and to immediately go rewrite everything in lowlevel win32 code, guess again.
